//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_Manage.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> SuburbId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string RuralDelivery { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Initials { get; set; }
        public string BusinessPhoneNumber { get; set; }
        public string MobilePhoneNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string AdditionalPhoneNumber { get; set; }
        public string eMail1 { get; set; }
        public string eMail2 { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> INZPosition { get; set; }
        public Nullable<bool> INZMember { get; set; }
        public string graphId { get; set; }
    }
}
